---
# tasks file for 2do_parcial
- name: "Crear directorios"
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "/tmp/2do_parcial/alumno"
    - "/tmp/2do_parcial/equipo"

- name: "Template datos_alumno"
  template:
    src: "datos_alumno.j2"
    dest: "/tmp/2do_parcial/alumno/datos_alumno.txt"

- name: "Template datos_equipo"
  template:
    src: "datos_equipo.j2"
    dest: "/tmp/2do_parcial/equipo/datos_equipo.txt"

- name: "Configurar sudoers para el grupo 2PSupervisores"
  lineinfile:
    path: /etc/sudoers
    state: present
    line: "%2PSupervisores ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

